# Copyright 2021 VMware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
  - image: controller-image
    path: .
    pack:
      build:
        builder: paketobuildpacks/builder:tiny
destinations:
  - image: controller-image
    newImage: projectcartographer/cartographer-controller
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartographer-controller
  namespace: cartographer-system
spec:
  selector:
    matchLabels:
      app: cartographer-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: cartographer-controller
    spec:
      serviceAccount: cartographer-controller
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: cartographer-webhook
      containers:
        - name: cartographer-controller
          image: controller-image
          args:
            - -cert-dir=/cert
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          volumeMounts:
            - mountPath: /cert
              name: cert
              readOnly: true
          resources:
            limits:
              cpu: 1
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
