name: 'Welcome New Contributors'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet the contributor'
        uses: garg3133/welcome-new-contributors@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello @contributor-name! Welcome to the Cartographer community and thank you for opening your first issue, we appreciate your contributions'
          pr-message: 'Hello @contributor-name!, thanks for opening your first Pull Request. Someone will review it soon. Thank you for committing to make Cartographer better'
